mv Pictures/袋.jpg Pictures/Bag.jpg
mv Pictures/波.png Pictures/Ball.png
mv Pictures/蕉.png Pictures/Banana.png
mv Pictures/床.jpg Pictures/Bed.jpg
mv Pictures/雀.jpg Pictures/Bird.jpg
mv Pictures/餅.png Pictures/Biscuits.png
mv Pictures/船.png Pictures/Boat.png
mv Pictures/書.jpg Pictures/Book.jpg
mv Pictures/樽.png Pictures/Bottle.png
mv Pictures/碗.gif Pictures/Bowl.gif
mv Pictures/盒.png Pictures/Box.png
mv Pictures/包.jpeg Pictures/Bread.jpeg
mv Pictures/鈕.png Pictures/Button.png
mv Pictures/糖.png Pictures/Candy.png
mv Pictures/車.png Pictures/Car.png
mv Pictures/貓.gif Pictures/Cat.gif
mv Pictures/凳.jpg Pictures/Chair.jpg
mv Pictures/雞.png Pictures/Chicken.png
mv Pictures/鐘.png Pictures/Clock.png
mv Pictures/梳.jpg Pictures/Comb.jpg
mv Pictures/杯.jpeg Pictures/Cup.jpeg
mv Pictures/狗.gif Pictures/Dog.gif
mv Pictures/門.gif Pictures/Door.gif
mv Pictures/櫃.jpg Pictures/Drawer.jpg
mv Pictures/裙.jpg Pictures/Dress.jpg
mv Pictures/鴨.jpg Pictures/Duck.jpg
mv Pictures/耳.png Pictures/Ear.png
mv Pictures/蛋.jpg Pictures/Egg.jpg
mv Pictures/眼.png Pictures/Eye.png
mv Pictures/腳.png Pictures/Feet.png
mv Pictures/魚.jpg Pictures/Fish.jpg
mv Pictures/花.png Pictures/Flower.png
mv Pictures/叉.png Pictures/Fork.png
mv Pictures/草.jpg Pictures/Grass.jpg
mv Pictures/手.png Pictures/Hand.png
mv Pictures/帽.png Pictures/Hat.png
mv Pictures/心.png Pictures/Heart.png
mv Pictures/馬.jpg Pictures/Hourse.jpg
mv Pictures/屋.png Pictures/House.png
mv Pictures/刀.jpg Pictures/Knife.jpg
mv Pictures/燈.jpg Pictures/Lamp.jpg
mv Pictures/葉.gif Pictures/Leaf.gif
mv Pictures/嘴.jpg Pictures/Mouth.jpg
mv Pictures/針.png Pictures/Needle.png
mv Pictures/面.jpg Pictures/Noodle.jpg
mv Pictures/鼻.gif Pictures/Nose.gif
mv Pictures/橙.png Pictures/Orange.png
mv Pictures/褲.gif Pictures/Pants.gif
mv Pictures/紙.jpg Pictures/Paper.jpg
mv Pictures/梨.png Pictures/Pear.png
mv Pictures/琴.jpg Pictures/Piano.jpg
mv Pictures/豬.jpg Pictures/Pig.jpg
mv Pictures/碟.jpeg Pictures/Plate.jpeg
mv Pictures/兔.jpg Pictures/Rabbit.jpg
mv Pictures/飯.png Pictures/Rice.png
mv Pictures/衫.png Pictures/Shirt.png
mv Pictures/鞋.png Pictures/Shoe.png
mv Pictures/蝦.jpg Pictures/Shrimp.jpg
mv Pictures/蛇.png Pictures/Snake.png
mv Pictures/襪.png Pictures/Socks.png
mv Pictures/羹.gif Pictures/Spoon.gif
mv Pictures/星.png Pictures/Star.png
mv Pictures/石.jpg Pictures/Stone.jpg
mv Pictures/枱.png Pictures/Table.png
mv Pictures/牙.jpg Pictures/Teeth.jpg
mv Pictures/樹.jpg Pictures/Tree.jpg
mv Pictures/turtle.jpg Pictures/Turtleurtle.jpg
mv Pictures/遮.jpg Pictures/Umbrella.jpg
mv Pictures/菜.jpg Pictures/Vegetable.jpg
mv Pictures/水.png Pictures/Water.png
mv Pictures/窗.jpg Pictures/Window.jpg